### PR TITLE
Add the talk on build modes.

### PR DESCRIPTION
**Pull request by justinas**

### CODE REVIEW

**Comment by ernestas-poskus** [comment]
@justinas is it possible to export to pdf ?

**Comment by justinas** [comment]
@ernestas-poskus will try.

**Comment by ernestas-poskus** [comment]
@justinas did you manage to export to PDF ?

**Comment by justinas** [comment]
Sorry it took a while. Finally managed to export a PDF.

**Comment by ernestas-poskus** [comment]
thanks, no problem :8ball:

**Pull request merged**
